### ISSUE TITLE
Set Up Node Initially

### ISSUE THREAD

**Issue by jonathandavidpollock** [jonathandavidpollock/FireshouseSubs#1]
Set up node initial structure of project with Express. Please use ES6 syntax.

**Comment by mykahT18** [comment]
I finished the initial setup of the project. I set up one route to check and see if it was working. To see the "Hello World" on the browser here is the route "http://localhost:3000/api/v1". On another note I put an env.example file for everyone. @carlosjunod when you set the database up you can use that to make your own. I also put all of our code into the src folder like Chris said too. To run the api just use the npm start command. 😁
