### ISSUE TITLE
Create Simple Illustration For Models

### ISSUE THREAD

**Issue by jonathandavidpollock** [jonathandavidpollock/FireshouseSubs#2]
These illustrations should contain the three tables: Products, Customers, and Orders. Please include the Schema types, References, and Column Names.

**Comment by carlosjunod** [comment]
hey @jonathandavidpollock, are we using MongoDB or MariaDB?

**Comment by carlosjunod** [comment]
Here is a diagram.
Let me know if there are any suggestion.

[FHOrderApi_diagram.pdf](https://github.com/jonathandavidpollock/FireshouseSubs/files/1272461/FHOrderApi_diagram.pdf)

**Comment by mykahT18** [comment]
Looks good @carlosjunod

**Comment by jonathandavidpollock** [comment]
Excellent work @carlosjunod. Glad to have you on the team!

**Comment by jonathandavidpollock** [comment]
This issue has been closed.

**Comment by carlosjunod** [comment]
don't close it yet :), I have to make slight modifications to the data structure, (eg. I changed the array for an JavaScript object instead)

**Comment by jonathandavidpollock** [comment]
The issue has been reopened.
