### ISSUE TITLE
Create Models

### ISSUE THREAD

**Issue by jonathandavidpollock** [jonathandavidpollock/FireshouseSubs#4]
Create the 3 models discussed in class today. Match the schema with the diagram you draw. The three models should be named OrderModel.js, ProductModel.js, and CustomerModel.js. Please put these files into the Models folder.

**Comment by carlosjunod** [comment]
Can I change the names of the files? as we are working in a MVC pattern, I think using a different naming will be better, those files will be already in a folder called models. (I suggest: Order.js, Product.js, Customer.js). tell me what you think, thanks (anyways I'm working, I can rename the files any moment)

**Comment by jonathandavidpollock** [comment]
Sounds great. Do it.
